version: 0.2

env:
  variables:
    DB_USERNAME: admin
    DB_PASSWORD: adminSP12
    CLUSTER_NAME: my-cluster
    AWS_REGION: us-east-1
    AWS_ACCOUNT_ID: 026090550003
    IMAGE_NAME: online-banking

phases:
  install:
    commands:
      - echo Installing dependencies...
      - dnf install -y unzip wget curl python3-pip --allowerasing

      # Install kubectl
      - curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
      - chmod +x kubectl && mv kubectl /usr/local/bin/

      # Upgrade AWS CLI
      - pip3 install --upgrade awscli

      # Install Trivy
      - echo Installing Trivy...
      - wget https://github.com/aquasecurity/trivy/releases/download/v0.50.2/trivy_0.50.2_Linux-64bit.tar.gz
      - tar zxvf trivy_0.50.2_Linux-64bit.tar.gz
      - mv trivy /usr/local/bin/


  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

      # Get RDS endpoint
      - export RDS_ENDPOINT=$(aws rds describe-db-instances --query "DBInstances[?DBName=='mydb'].Endpoint.Address" --output text --region $AWS_REGION)
      - echo "RDS_ENDPOINT=$RDS_ENDPOINT"

      - export IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:latest"

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME:latest $IMAGE_URI

      - echo Scanning image with Trivy...
      - mkdir -p trivy-reports
      - trivy image --severity HIGH,CRITICAL --exit-code 0 --format table -o trivy-reports/report.txt $IMAGE_NAME:latest || true

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $IMAGE_URI

      - echo Preparing Kubernetes manifests...
      - mkdir -p k8s-out
      - sed "s|IMAGE_PLACEHOLDER|$IMAGE_URI|g" k8s/deployment.yaml > k8s-out/deployment.yaml
      - cp k8s/service.yaml k8s-out/service.yaml

      - echo Build and Scan Complete

artifacts:
  base-directory: .
  files:
    - k8s-out/deployment.yaml
    - k8s-out/service.yaml
    - trivy-reports/report.txt
