version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Docker...
      - nohup /usr/local/bin/dockerd-entrypoint.sh &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo Docker is ready.
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 026090550003.dkr.ecr.us-east-1.amazonaws.com

  pre_build:
    commands:
      - echo Build started on `date`
      - echo Compiling the application...
      - mvn clean package -DskipTests

  build:
    commands:
      - echo Building Docker image...
      - docker build -t online-banking:latest .
      - docker tag online-banking:latest 026090550003.dkr.ecr.us-east-1.amazonaws.com/online-banking:latest

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push 026090550003.dkr.ecr.us-east-1.amazonaws.com/online-banking:latest
      - echo Build completed on `date`

artifacts:
  files:
    - target/online-banking-0.0.1-SNAPSHOT.jar
