version: 0.2

env:
  variables:
    DB_USERNAME: admin
    DB_PASSWORD: adminSP12
    CLUSTER_NAME: my-cluster
    AWS_REGION: us-east-1
    AWS_ACCOUNT_ID: 026090550003

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y gettext unzip curl
      - curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
      - chmod +x kubectl && mv kubectl /usr/local/bin/
      - pip install --upgrade awscli

  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - export RDS_ENDPOINT=$(aws rds describe-db-instances --query "DBInstances[?DBName=='mydb'].Endpoint.Address" --output text --region $AWS_REGION)
      - echo "RDS_ENDPOINT=$RDS_ENDPOINT"
      - export IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/online-banking:latest" # Define IMAGE_URI here

  build:
    commands:
      - docker build -t online-banking .
      - docker tag online-banking:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/online-banking:latest

  post_build:
    commands:
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/online-banking:latest
      - echo Preparing Kubernetes manifests...
      - echo "Listing files in current directory:"
      - ls -la
      - echo "Listing files in k8s directory:"
      - ls -la k8s/ # Add this to verify contents of k8s folder
      - pwd
      - mkdir -p k8s-out
      - pwd
      - sed "s|IMAGE_PLACEHOLDER|$IMAGE_URI|g" k8s/deployment.yaml > k8s-out/deployment.yaml 
      - pwd
      - cp k8s/service.yaml k8s-out/service.yaml 
      - echo Done preparing artifacts.
      - echo "Configuring kubectl and creating namespace..."
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
      # - kubectl get namespace online-banking || kubectl create namespace online-banking
      - echo "Namespace 'online-banking' ensured."

artifacts:
  base-directory: k8s-out
  files:
    - deployment.yaml
    - service.yaml
