version: 0.2

env:
  variables:
    DB_USERNAME: admin
    DB_PASSWORD: adminSP12
    CLUSTER_NAME: my-cluster
    AWS_REGION: us-east-1
    AWS_ACCOUNT_ID: 026090550003

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y gettext unzip curl
      - curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
      - chmod +x kubectl && mv kubectl /usr/local/bin/
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - export RDS_ENDPOINT=$(aws rds describe-db-instances --query "DBInstances[?DBName=='mydb'].Endpoint.Address" --output text --region $AWS_REGION)
      - echo "RDS_ENDPOINT=$RDS_ENDPOINT"
      - export IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/online-banking:latest"

  build:
    commands:
      - echo Building Docker image...
      - docker build -t online-banking .
      - docker tag online-banking:latest $IMAGE_URI

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $IMAGE_URI
      - echo Preparing Kubernetes manifests...
      - mkdir -p k8s-out
      - sed "s|IMAGE_PLACEHOLDER|$IMAGE_URI|g" k8s/deployment.yaml > k8s-out/deployment.yaml
      - cp k8s/service.yaml k8s-out/service.yaml
      - cp k8s/namespace.yaml k8s-out/namespace.yaml
      - echo Configuring kubectl...
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
      - echo Applying namespace manifest...
      - kubectl apply -f k8s-out/namespace.yaml
      - echo Applying deployment and service...
      - kubectl apply -f k8s-out/deployment.yaml -f k8s-out/service.yaml
      - echo Deployment and service applied successfully.

artifacts:
  base-directory: k8s-out
  files:
    - deployment.yaml
    - service.yaml
    - namespace.yaml
