version: 0.2

env:
  variables:
    DB_USERNAME: admin
    DB_PASSWORD: adminSP12
    CLUSTER_NAME: my-cluster
    AWS_REGION: us-east-1
    AWS_ACCOUNT_ID: 026090550003
    IMAGE_NAME: online-banking

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum update -y
      - yum install -y unzip wget python3-pip gnupg tar
      - pip3 install --upgrade awscli
      - curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
      - chmod +x kubectl && mv kubectl /usr/local/bin/
      - echo Installing Trivy...
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - echo "Trivy installed successfully."

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - export RDS_ENDPOINT=$(aws rds describe-db-instances --query "DBInstances[?DBName=='mydb'].Endpoint.Address" --output text --region $AWS_REGION)
      - echo "RDS_ENDPOINT=$RDS_ENDPOINT"
      - export IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}:latest"

  build:
    commands:
      - echo Building Docker image...
      - doc
