version: 0.2

env:
  variables:
    DB_USERNAME: admin
    DB_PASSWORD: adminSP12

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing envsubst...
      - yum install -y gettext

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Fetching RDS endpoint...
      - export RDS_ENDPOINT=$(aws rds describe-db-instances --query "DBInstances[?DBName=='mydb'].Endpoint.Address" --output text --region $AWS_REGION)
      - echo RDS_ENDPOINT=$RDS_ENDPOINT

  build:
    commands:
      - echo Building Docker image...
      - docker build -t online-banking .
      - docker tag online-banking:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/online-banking:latest

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/online-banking:latest
      - echo Replacing placeholders in deployment template...
      - mkdir -p k8s
      - envsubst < k8s/deployment-template.yaml > k8s/deployment.yaml
      - envsubst < appspec-template.yaml > appspec.yaml

artifacts:
  files:
    - appspec.yaml
    - k8s/deployment.yaml
