version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    CLUSTER_NAME: eks-cluster
    ECR_REPO_NAME: online-banking
    IMAGE_TAG: latest

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 20
    commands:
      - echo Installing Maven...
      - mvn --version
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 026090550003.dkr.ecr.$AWS_REGION.amazonaws.com
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Compiling the application with Maven...
      - mvn clean package -DskipTests
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REPO_NAME:$IMAGE_TAG .
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG 026090550003.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 026090550003.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
      - echo Updating kubeconfig for EKS...
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
      - echo Applying Kubernetes manifests...
      - kubectl apply -f k8s/
artifacts:
  files:
    - target/online-banking-0.0.1-SNAPSHOT.jar
