version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 20
    commands:
      - echo "Installing dependencies..."
      - echo "Maven version:"
      - mvn --version
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 026090550003.dkr.ecr.us-east-1.amazonaws.com
      - echo "Installing kubectl..."
      - curl -o kubectl https://s3.us-east-1.amazonaws.com/amazon-eks/1.27.6/2023-10-11/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
  pre_build:
    commands:
      - echo "Starting pre-build..."
      - echo "Building Spring Boot application..."
      - mvn clean package -DskipTests
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t online-banking:latest .
      - docker tag online-banking:latest 026090550003.dkr.ecr.us-east-1.amazonaws.com/online-banking:latest
  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 026090550003.dkr.ecr.us-east-1.amazonaws.com/online-banking:latest
      - echo "Updating kubeconfig for EKS cluster..."
      - aws eks update-kubeconfig --region us-east-1 --name eks-cluster
      - echo "Verifying cluster access..."
      - kubectl get nodes
      - echo "Applying Kubernetes manifests from k8s/ directory..."
      - kubectl apply -f k8s/
artifacts:
  files:
    - target/online-banking-0.0.1-SNAPSHOT.jar
