version: 0.2

env:
  variables:
    DB_USERNAME: admin
    DB_PASSWORD: adminSP12
    CLUSTER_NAME: my-cluster
    AWS_REGION: us-east-1
    AWS_ACCOUNT_ID: 026090550003

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y gettext unzip curl
      - curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
      - chmod +x kubectl && mv kubectl /usr/local/bin/
      - pip install --upgrade awscli

  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - export RDS_ENDPOINT=$(aws rds describe-db-instances --query "DBInstances[?DBName=='mydb'].Endpoint.Address" --output text --region $AWS_REGION)
      - echo "RDS_ENDPOINT=$RDS_ENDPOINT"

  build:
    commands:
      - docker build -t online-banking .
      - docker tag online-banking:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/online-banking:latest

  post_build:
    commands:
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/online-banking:latest
      - envsubst < k8s/deployment.yaml > k8s/deployment-processed.yaml
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
      - kubectl get namespace online-banking || kubectl create namespace online-banking
      - kubectl apply -f k8s/deployment-processed.yaml -n online-banking --validate=false
      - kubectl apply -f k8s/service.yaml -n online-banking
      - kubectl rollout status deployment/online-banking -n online-banking
      - kubectl get service online-banking-service -n online-banking -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' || kubectl get service online-banking-service -n online-banking -o jsonpath='{.status.loadBalancer.ingress[0].ip}'

artifacts:
  files:
    - k8s/deployment-processed.yaml
