version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install -g @angular/cli
      - cd frontend && npm install && cd ..

  pre_build:
    commands:
      - echo Build phase started...

  build:
    commands:
      - echo Building Angular app...
      - cd frontend
      - ng build --configuration production
      - cd ..
      - echo Building Spring Boot app...
      - cd backend
      - mvn clean package -DskipTests
      - cd ..

  post_build:
    commands:
      - echo Packaging frontend with backend...
      - mkdir -p backend/src/main/resources/static
      - cp -r frontend/dist/frontend/* backend/src/main/resources/static/
      - echo Build and package completed.

artifacts:
  files:
    - backend/target/*.jar
  discard-paths: yes
