apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-banking
  labels:
    app: online-banking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: online-banking
  template:
    metadata:
      labels:
        app: online-banking
    spec:
      containers:
        - name: online-banking
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://onlinebankingstack-rdsinstance-yqwzoma6hm0r.clceiq8g4r09.us-east-1.rds.amazonaws.com:3306/mydb
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: adminSP12
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
