apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-banking
  labels:
    app: online-banking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: online-banking
  template:
    metadata:
      labels:
        app: online-banking
    spec:
      containers:
        - name: online-banking
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/online-banking:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://${RDS_ENDPOINT}:3306/mydb
            - name: SPRING_DATASOURCE_USERNAME
              value: ${DB_USERNAME}
            - name: SPRING_DATASOURCE_PASSWORD
              value: ${DB_PASSWORD}
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
