apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-banking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: online-banking
  template:
    metadata:
      labels:
        app: online-banking
    spec:
      containers:
        - name: online-banking
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/online-banking:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://${RDS_ENDPOINT}:3306/mydb
            - name: SPRING_DATASOURCE_USERNAME
              value: ${DB_USERNAME}
            - name: SPRING_DATASOURCE_PASSWORD
              value: ${DB_PASSWORD}
---
apiVersion: v1
kind: Service
metadata:
  name: online-banking-service
spec:
  type: LoadBalancer
  selector:
    app: online-banking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
