apiVersion: v1
kind: Service
metadata:
  name: online-banking-service
  namespace: online-banking
spec:
  type: LoadBalancer
  selector:
    app: online-banking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
